function [] = parsave(filename,results_non_total,results_positive_total,results_negative_total,...
        theta_est,ifgood,data,gene)
save(filename,'results_non_total','results_positive_total','results_negative_total',...
        'theta_est','ifgood','data','gene')
end